# -*- coding: utf-8 -*-
"""Ejercicios 09102025 Estructura de datos I

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yOmG0qcRX83rquGtyiaKP1liHxo0LuF
"""

#Área y perímetro de un cuadrado
#l = lado del cuadrdo
#ar = área
# pe = perímetro
l = float(input("Digite un lado del cuadrado: "))
ar = l ** 2
pe = 4 * l
print(f"El área del cuadrado es: {ar}")
print(f"El perímetro del cuadrado es: {pe}")

"""Area y perimetro de un triangulo isósceles
b= base del triangulo
a = altura del triángulo
c = lado restante restante
ar = area
pe = perímetro"""
b = float(input("Digite la base del triángulo: "))
a = float(input("Digite la altura del triángulo: "))
c = float(input("Digite un lado del triángulo diferente a la base: "))
ar = (b*a)/2
pe = b + c + c
print(f"El área del triángulo es: {ar}")
print(f"El perímetro del triángulo es: {pe}")

"""Area y perimetro de un octágono
l = lado del octágono
ar = area
pe= perímetro"""
l = float(input("Digite un lado del octágono: "))
ar = 2 * (l**2) * (1 + (2**(1/2)))
pe = l * 8
print(f"El área del octágono es: {ar}")
print(f"El perímetro del octágono es: {pe}")

#Definir si un numero entero es PAR o IMPAR
# n = variable como un numero
n = int(input("Digite un número entero: "))
if n % 2 == 0:
    print(f"El número {n} es PAR ")
else:
    print(f"El número {n} es IMPAR")