# -*- coding: utf-8 -*-
"""Ejercicios 101025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShAhAv4aYLaVWseMOKwbMEls72uCH863

1. Cálculo de la media de n observaciones numéricas
"""

n = int(input("Ingrese el número de observaciones: "))
suma = 0
for i in range(n):
  num = float(input(f"Ingrese el numero {i+1}: "))
  suma += num

media = suma / n
print(f"La media de las {n} observaciones numércas es: {media}")

"""2. Determinar si un número es primo o no"""

num = int(input("Ingresa un número entero : "))
cont = 0
for i in range(1, num + 1):
  if num % i == 0:
    cont += 1

if cont == 2:
  print(f"El número {num} es primo")
else:
  print(f"El número {num} no es primo")

"""5. Receta para preparar spaghetti alla napoletana"""

pasos = [
    "Paso 1: Busca los siguientes ingredientes para cocinar spaghetti alla napoletana para 2 personas : 1/2 cebolla, 2 dientes de ajo, 2 cucharadas soperas de aceite de oliva, 4 tomates sin piel en conserva, 1 cucharada pequeña de azucar, 1 pizca de sal, 1 pizca de pimienta negra molida, 10g de sal gruesa, 180g de espaguetis, 1 puñado de hojas de albahaca fresca, Queso parmesano al gusto",
    "Paso 2: Preparar la salsa napolitana. Para ello pelamos y cortamos en daditos media cebolla y 2 dientes de ajo",
		"Paso 3: En una sartén, echamos 2 cucharadas soepras de aceite de oliva extra virgen, lo calentamos fuego medio y cuando esté caliente añadimos la cebolla y los dientes de ajo picados. Sofreímos durante unos 8 minutos o hasta que veamos que la cebolla está tierna",
    "Paso 4: Añadimos a la sartén 4 tomates en conserva y condimentos  con 1 cucharada pequeña de azucar que ayuda a corregir la acidez del tomate, 1 pizca de sal y 1 pizca de pimienta negra molida. Continuamoa a la cocción 15 minutos durante los cuales, iremos deshaciendo el tomate con la ayuda de una cuchara de madera",
    "Paso 5: Mientras el tomate se sofríe, ponemos a calentar una olla con abundante agua. Cuando rompa a hervir añadimos 10 gramos de sal gruesa y 180 gramos de espaguetis. Removemos durante unos segundos para que la pasta no se pegue entre ella y cocemos durante el tiempo que indique el fabricante, en este caso 9 minutos para que los espaguetis queden al dente.",
    "Paso 6: A la vez que cocemos la pasta, continuamos con la preparación de la salsa napolitana. Es importante cuadrar bien los tiempos para que la salsa esté siempre lista antes que la pasta. La pasta nunca debe esperar por la salsa porque corremos el riesgo de que se pase y no hay nada peor en una receta de pasta que esta no esté al punto. Agregamos a la salsa un puñado de hojas de albahaca fresca troceada y continuamos la cocción un par de minutos más.",
    "Paso 7: Finalizado el tiempo de cocción de los espaguetis, los escurrimos y los añadimos directamente sobre la salsa napolitana. Mezclamos bien para que los ingredientes y los sabores se integren",
    "Paso 8: Servimos los espaguetis a la napolitana inmediatamente y los emplatamos rallando por encima queso parmesano al gusto de cada comensal."
]

print("Receta de como hacer spaghettis alla napoletana")
print("Escribr 'si' para ver cada paso. \n")

for paso in pasos:
  respuesta = input("¿Quieres ver el siguiente paso? (si/no): ").lower()
  if respuesta == "si":
    print(paso)
  else:
    print("fin receta")
    break

print("Fin de la receta, disfruta!!!")